In [1]:
#Sample Data

import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.3, -1.7, 5.8],
                        [-1.9, 2.3, 3.8],
                        [0.2, -7.4, 5.6],
                        [5.3, 2.5, -5.4]])

sample_data

array([[ 2.3, -1.7,  5.8],
       [-1.9,  2.3,  3.8],
       [ 0.2, -7.4,  5.6],
       [ 5.3,  2.5, -5.4]])

In [2]:
sample_data.shape   #Untuk mengetahui jumlah kolom dan baris

(4, 3)

In [3]:
#Teknik Pertama: Binarisation

sample_data

array([[ 2.3, -1.7,  5.8],
       [-1.9,  2.3,  3.8],
       [ 0.2, -7.4,  5.6],
       [ 5.3,  2.5, -5.4]])

In [6]:
#Jika lebih besar dari thresholdnya akan ditransformasikan menjadi 1 jika kurang dari 0.5 akan ditransformasikan menjadi nilai 0

preprocessor = preprocessing.Binarizer(threshold=0.5)  #Membentuk objek Binarizernya
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [7]:
#Teknik 2: Scaling

sample_data

array([[ 2.3, -1.7,  5.8],
       [-1.9,  2.3,  3.8],
       [ 0.2, -7.4,  5.6],
       [ 5.3,  2.5, -5.4]])

In [8]:
#Proses MinMaxScaler ini digunakan untuk mengubah skala nilai terkecil dan terbesar dari dataset yang dimiliki ke skala tertentu

preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1)) #Parameter feature_range membutuhkan data bertipe tuple
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.58333333, 0.57575758, 1.        ],
       [0.        , 0.97979798, 0.82142857],
       [0.29166667, 0.        , 0.98214286],
       [1.        , 1.        , 0.        ]])

In [9]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.58333333, 0.57575758, 1.        ],
       [0.        , 0.97979798, 0.82142857],
       [0.29166667, 0.        , 0.98214286],
       [1.        , 1.        , 0.        ]])

In [10]:
#Teknik 3: Normalisasi, L1:Normalisation:Least Absolute Deviations

sample_data

array([[ 2.3, -1.7,  5.8],
       [-1.9,  2.3,  3.8],
       [ 0.2, -7.4,  5.6],
       [ 5.3,  2.5, -5.4]])

In [11]:
L1_normalised_data = preprocessing.normalize(sample_data, norm='l1') #parameter norm diberi string l1, normalisasi l1 ini akan berasosiasi dengan normalisasi yang menerapkan Least Absolute Deviations   
L1_normalised_data

array([[ 0.23469388, -0.17346939,  0.59183673],
       [-0.2375    ,  0.2875    ,  0.475     ],
       [ 0.01515152, -0.56060606,  0.42424242],
       [ 0.40151515,  0.18939394, -0.40909091]])

In [12]:
#L2 Normalisation: Least Squares

sample_data

array([[ 2.3, -1.7,  5.8],
       [-1.9,  2.3,  3.8],
       [ 0.2, -7.4,  5.6],
       [ 5.3,  2.5, -5.4]])

In [13]:
L2_normalised_data = preprocessing.normalize(sample_data, norm='l2') #parameter norm diberi string l2, normalisasi l2 ini akan berasosiasi dengan teknik normalisasi Least Squares 
L2_normalised_data

array([[ 0.35566065, -0.26287961,  0.89688339],
       [-0.39328119,  0.47607723,  0.78656238],
       [ 0.02154652, -0.79722127,  0.60330258],
       [ 0.66510315,  0.3137279 , -0.67765227]])